### ISSUE TITLE
Incident mit weiteren Feldern anzeigen: Trailer, Children-Involved, Bike-Type

### ISSUE THREAD

**Issue by adriangronau** [simra-project/SimRa-Visualization#124]

**Comment by adriangronau** [comment]
- [x] Es wird anzeigt ob ein Trailer vorhanden war (wenn `Feld === true`)
- [x] Es wird anzeigt ob Kinder beteiligt waren (wenn `Feld === true`)

Der Bike-Type wird nicht angezeigt weil die Information nicht aus der API kommt.

**Comment by 7imo** [comment]
wird gefixt mit #125
