### ISSUE TITLE
Filter erweitern: Trailer, Bike-Type, Children-involved, Description, etc.

### ISSUE THREAD

**Issue by adriangronau** [simra-project/SimRa-Visualization#125]
Frontend & Backend

**Comment by 7imo** [comment]
Im backend (in der incident filter api) gibts diese funktionen schon

**Comment by 7imo** [comment]
Filter im Backend / Incident Filter API done, muss also nur noch im Frontend implementiert werden - der Feature Branch ist: feature/incident_filter_extension

**Comment by adriangronau** [comment]
Ein API-Call für Filter und Area
