### ISSUE TITLE
Filter für fehlerhafte Daten

### ISSUE THREAD

**Issue by adriangronau** [simra-project/SimRa-Visualization#22]
Acceptance criteria:
- [ ] Die unten genannten Löschkriterien führen dazu dass diese Routes entfernt werden
- [ ] Die gefilterten Daten werden entsprechend gespeichert

**Comment by sehof-git** [comment]
Löschkriterien:
Daten löschen, wenn
- zu kurze Distanz 
- zu kurze Zeit
- zu hohe Durchschnittsgeschwindigkeit
- User hat vergessen Ride zu beenden
- falsche GPS Daten (eg. New York)

**Comment by konskoehler** [comment]
Habe _false GPS (zB NYC)_ zunächst ausgelassen. Wird gefixt, wenn wir uns der Problematik der mehreren Städte annehmen.
