### ISSUE TITLE
Recherche Mapping Route auf OSM Straßen

### ISSUE THREAD

**Issue by adriangronau** [simra-project/SimRa-Visualization#23]
Acceptance criteria:
- [x] Es wurde recherchiert ob es möglich ist Routes auf (sehr) nahegelegte Straßen bzw. Pfade in OSM zu mappen
- [x] Falls dies möglich ist wird eine entsprechende Demo erstellt
- [x] Das Ergebnis wird entsprechend dokumentiert

**Comment by konskoehler** [comment]
see https://drive.google.com/drive/folders/1AmMkT09e82KjhPT8bqvPMjbyDPUwUMzc
