### ISSUE TITLE
2 Algorithmen testen (Kalman-Filter & Douglas-Peucker)

### ISSUE THREAD

**Issue by adriangronau** [simra-project/SimRa-Visualization#5]
Acceptance criteria:
 - [x] der Kalman-Filter wird für Positionsdaten getestet
 - [x] der Douglas-Peucker-Algorithmus wird für Positionsdaten getestet
 - [x] beide Algorithmen werden verglichen und das Ergebnis plus gesammelte Erfahrungen werden notiert (Slack, Github Issues, Textdatei)

**Comment by konskoehler** [comment]
please review: https://drive.google.com/drive/folders/1pHV1Ki9NoC2ZVP7kcAXmtm0FdoqodIpt

**Comment by adriangronau** [comment]
Looks perfect!
